### ISSUE TITLE
"grep" in selectSolution can find the wrong files

### ISSUE THREAD

**Issue by lbeltrame** [gavinha/TitanCNA#10]
I had some samples called `foo_CAP` and `foo_CAP-DEEP`.

The code in `selectSolution.R` does a grep on the file list (also valid for ploidy of 3 and 4):

```r
phi2Samples <- grep(id, phi2Files, value=T)
```

However in this case it will match **both** files and cause inconsistent results to be written. As the pattern in default cases is id plus an underscore, a solution like this may work:

```r
phi2Samples <- grep(paste0(id, "_"), phi2Files, value=T)
```

Exact string matching won't help as it will still catch the shorter string contained in the long one.

**Comment by gavinha** [comment]
PR #73 fixes this issue
