### ISSUE TITLE
Mappability track

### ISSUE THREAD

**Issue by jgockley62** [gavinha/TitanCNA#15]
Hi,

Is there any chance that you have an hg38 mappability file fo rthe 10x Whole Genome Sequencing pipeline (map_hg19_10kb.wig)? I can make them via the gem-mappability tool, but a 10kb length is super inefficient in processing time.

**Comment by gavinha** [comment]
Hi Jake,

Unfortunately, we haven't generated a mappability file yet but we can look into it.  Thanks for bringing up the gem-mappability tool.  We were having a little bit of trouble generating it using Bowtie.

Thanks,
Gavin

**Comment by gavinha** [comment]
10kb gc and map wig files are included in the ichorCNA GitHub repo
See https://github.com/broadinstitute/ichorCNA/commit/1d54a1fd4d8bd88aa0217791482be65bfe599db5
and issue https://github.com/broadinstitute/ichorCNA/issues/35
