### ISSUE TITLE
Script input error

### ISSUE THREAD

**Issue by jgockley62** [gavinha/TitanCNA#16]
Hi,

I've decided to move ahead in hg38 with a smaller bin size of mapability and GC% as the mapability file is much quicker to make at smaller BED intervals. The first TenX script doesn't appear to be pulling in the haplotype.R script. Any advice on what I'm doing wrong?

Rscript getMoleculeCoverage.R 
       --id TMI40424 
       -l TitanCNA/scripts/
       -d Final_GCandMAP/ 
       -t TMI40424_Tumor.10kb.bxTile.chrX.bed 
       -n TMI40424_Germline.10kb.bxTile.chrX.bed 
       --minReadsPerBX=4 
       --chrs \"X\" 
       --outDir TMI40424/ 
       --centromere GRCh38.p13_centromere_UCSC-gapTable.txt

Error: 

Loading required package: grid
Error: could not find function "loadBXcountsFromBEDDir"
Execution halted

Best,
Jake

**Comment by gavinha** [comment]
Hi Jake,

Sorry for the inconvenience. There are 2 solutions:
1) Use the `--libdir` argument and specify the `TitanCNA/R/` directory containing the `haplotype.R` file.
2) I added `loadBXcountsFromBEDDir` to the namespace so it should work even without `--libdir`. However, just incase I messed up somewhere, you can use solution 1 and get started.

Best,
Gavin

**Comment by jgockley62** [comment]
Cool thanks. Thats working, for anyone else's reference just leave the R/ off TitanCNA/R/ because it's hard coded. It looks like there's an undefined function within the loadBXcountsFromBedDir function. I couldn't find that function in any of the TitanCNA/R/ scripts 

Error in loadBXcountsFromBEDDir(tumour_file, minReads = minReadsPerBX) : 
  could not find function "keepChr"
Execution halted

**Comment by gavinha** [comment]
Hi Jake,

These errors were happening because `getMoleculeCoverage.R` is out of date for performing the [ichorCNA](https://github.com/broadinstitute/ichorCNA/) analysis.  I use the ichorCNA (https://github.com/broadinstitute/ichorCNA/) package to perform the GC correction but ichorCNA has been updated since.  I've now synced up the analysis such that `getMoleculeCoverage.R` is similar to [runIchorCNA.R](https://github.com/broadinstitute/ichorCNA/blob/master/scripts/runIchorCNA.R).  

You should reinstall both [TitanCNA](https://github.com/gavinha/TitanCNA/) and [ichorCNA](https://github.com/broadinstitute/ichorCNA/) R packages from github.

Here are the changes you need to make to your current command line arguments:
1. Remove `--datadir` and use `--gcWig` to point to the path of the GC wig file
2. `--libdir` specifies the path of R source files that you wish to include in the script that is either new functions or modified functions to overload existing libraries. `haplotype.R` is now updated and `loadBXcountsFromBEDDir` should work now.  So using `--libdir` is not necessary. 

```
    # from the command line
    >Rscript TenX_scripts/getMoleculeCoverage.R --help
    Usage: TenX_scripts/getMoleculeCoverage.R [options]


    Options:
            -t TUMORBXDIR, --tumorBXDir=TUMORBXDIR
                    Path to directory containing tumor bed files for each chromosome containing BX tags.

            -n NORMALBXDIR, --normalBXDir=NORMALBXDIR
                    Path to directory containing normal bed files for each chromosome containing BX tags.

            --minReadsPerBX=MINREADSPERBX
                    Minimum number of reads per barcode.
            
            --gcWig=GCWIG
                    Path to GC-content WIG file; Required
                    
            --libdir=LIBDIR
                    Script library path to include new or modified source R files (optional). Default: [NULL]
                
            (... plus other options)  

```
Here is an example  
    
```
     Rscript getMoleculeCoverage.R --id test  \
        --tumorBXDir tumour_bxTile/ --normalBXDir normal_bxTile/ --minReadsPerBX 2 \
        --chrs "c(1:22, \"X\")" --outDir ../ \
        --centromere TenX_scripts/data/GRCh37.p13_centromere_UCSC-gapTable.txt \
        --gcWig ichorCNA/inst/extdata/gc_hg38_1000kb.wig \
        --libdir TitanCNA/R/
```

Best,
Gavin

**Comment by jgockley62** [comment]
Hey Gavin,

Still having some issues. Running as above errors out as such:
Rscript TitanCNA-master/scripts/TenX_scripts/getMoleculeCoverage.R \
 --id test 
 --tumorBXDir TMI40424/Chr22_Tumor \ 
 --normalBXDir TMI40424/Chr22_Germline \
 --minReadsPerBX 2 \
 --chrs "c(22)" \ 
 --outDir .. \
 --centromere GRCh38.p13_centromere_UCSC-gapTable.txt \
 --gcWig Final_GCandMAP/gc.hg38.50bp.wig \ 
 --libdir /home/jgockley/Programs/TitanCNA-master/R/

Output:
  Loading tumour files from TMI40424/Chr22_Tumor
  Loading BX counts from TMI40424/Chr22_Tumor
  TMI40424/Chr22_Tumor/Filt//TMI40424_Tumor.10kb.bxTile.chr22_Filt.bed
  Read 739393 rows and 4 (of 4) columns from 0.871 GB file in 00:00:27
  Error in tumour_doc[1, ] : 
    selecting rows: subscript contains NAs or out of bounds indices
    Calls: as.data.frame -> [ -> [
    Execution halted

The error happens in the LoadReadCountsFromWig() function, but the loadBXcountsFromBEDDir()
returns tumour_doc as: RangedData with 0 rows and 1 value column across 24 spaces

So that still might be the error?

**Comment by gavinha** [comment]
Hi Jake,

Which version of R are you using?  v3.3.x or 3.4.x?  I wonder if GenomeInfoDb for v3.4.x has changed the behavior of how it handles chromosome names which could have lead to no overlapping bins.

**Comment by jgockley62** [comment]
I'm using version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"

**Comment by jgockley62** [comment]
I do get some warnings when I load Titan though, initially I didn't think these were an issue though.
Warning messages:
1: replacing previous import ‘GenomicRanges::shift’ by ‘data.table::shift’ when loading ‘TitanCNA’
2: replacing previous import ‘data.table::first’ by ‘dplyr::first’ when loading ‘TitanCNA’
3: replacing previous import ‘IRanges::slice’ by ‘dplyr::slice’ when loading ‘TitanCNA’
4: replacing previous import ‘data.table::between’ by ‘dplyr::between’ when loading ‘TitanCNA’
5: replacing previous import ‘IRanges::collapse’ by ‘dplyr::collapse’ when loading ‘TitanCNA’
6: replacing previous import ‘GenomeInfoDb::intersect’ by ‘dplyr::intersect’ when loading ‘TitanCNA’
7: replacing previous import ‘data.table::last’ by ‘dplyr::last’ when loading ‘TitanCNA’
8: replacing previous import ‘GenomicRanges::setdiff’ by ‘dplyr::setdiff’ when loading ‘TitanCNA’
9: replacing previous import ‘GenomicRanges::union’ by ‘dplyr::union’ when loading ‘TitanCNA’
10: replacing previous import ‘IRanges::desc’ by ‘dplyr::desc’ when loading ‘TitanCNA’
11: replacing previous import ‘BiocGenerics::rowSums’ by ‘S4Vectors::rowSums’ when loading ‘VariantAnnotation’
12: replacing previous import ‘BiocGenerics::var’ by ‘S4Vectors::var’ when loading ‘VariantAnnotation’
13: replacing previous import ‘BiocGenerics::rowMeans’ by ‘S4Vectors::rowMeans’ when loading ‘VariantAnnotation’
14: replacing previous import ‘BiocGenerics::colSums’ by ‘S4Vectors::colSums’ when loading ‘VariantAnnotation’
15: replacing previous import ‘BiocGenerics::sd’ by ‘S4Vectors::sd’ when loading ‘VariantAnnotation’
16: replacing previous import ‘BiocGenerics::colMeans’ by ‘S4Vectors::colMeans’ when loading ‘VariantAnnotation’
17: replacing previous import ‘BiocGenerics::rowSums’ by ‘S4Vectors::rowSums’ when loading ‘GenomicFeatures’
18: replacing previous import ‘BiocGenerics::var’ by ‘S4Vectors::var’ when loading ‘GenomicFeatures’
19: replacing previous import ‘BiocGenerics::rowMeans’ by ‘S4Vectors::rowMeans’ when loading ‘GenomicFeatures’
20: replacing previous import ‘BiocGenerics::colSums’ by ‘S4Vectors::colSums’ when loading ‘GenomicFeatures’
21: replacing previous import ‘BiocGenerics::sd’ by ‘S4Vectors::sd’ when loading ‘GenomicFeatures’
22: replacing previous import ‘BiocGenerics::colMeans’ by ‘S4Vectors::colMeans’ when loading ‘GenomicFeatures’
23: replacing previous import ‘BiocGenerics::rowSums’ by ‘S4Vectors::rowSums’ when loading ‘rtracklayer’
24: replacing previous import ‘BiocGenerics::var’ by ‘S4Vectors::var’ when loading ‘rtracklayer’
25: replacing previous import ‘BiocGenerics::rowMeans’ by ‘S4Vectors::rowMeans’ when loading ‘rtracklayer’
26: replacing previous import ‘BiocGenerics::colSums’ by ‘S4Vectors::colSums’ when loading ‘rtracklayer’
27: replacing previous import ‘BiocGenerics::sd’ by ‘S4Vectors::sd’ when loading ‘rtracklayer’
28: replacing previous import ‘BiocGenerics::colMeans’ by ‘S4Vectors::colMeans’ when loading ‘rtracklayer’
29: replacing previous import ‘BiocGenerics::rowSums’ by ‘S4Vectors::rowSums’ when loading ‘GenomicAlignments’
30: replacing previous import ‘BiocGenerics::var’ by ‘S4Vectors::var’ when loading ‘GenomicAlignments’
31: replacing previous import ‘BiocGenerics::rowMeans’ by ‘S4Vectors::rowMeans’ when loading ‘GenomicAlignments’
32: replacing previous import ‘BiocGenerics::colSums’ by ‘S4Vectors::colSums’ when loading ‘GenomicAlignments’
33: replacing previous import ‘BiocGenerics::sd’ by ‘S4Vectors::sd’ when loading ‘GenomicAlignments’
34: replacing previous import ‘BiocGenerics::colMeans’ by ‘S4Vectors::colMeans’ when loading ‘GenomicAlignments’
35: replacing previous import ‘BiocGenerics::rowSums’ by ‘S4Vectors::rowSums’ when loading ‘BSgenome’
36: replacing previous import ‘BiocGenerics::var’ by ‘S4Vectors::var’ when loading ‘BSgenome’
37: replacing previous import ‘BiocGenerics::rowMeans’ by ‘S4Vectors::rowMeans’ when loading ‘BSgenome’
38: replacing previous import ‘BiocGenerics::colSums’ by ‘S4Vectors::colSums’ when loading ‘BSgenome’
39: replacing previous import ‘BiocGenerics::sd’ by ‘S4Vectors::sd’ when loading ‘BSgenome’
40: replacing previous import ‘BiocGenerics::colMeans’ by ‘S4Vectors::colMeans’ when loading ‘BSgenome’
41: replacing previous import ‘dplyr::select’ by ‘VariantAnnotation::select’ when loading ‘TitanCNA’

**Comment by jgockley62** [comment]
Hey Gavin currently getting the following error, would love some input on what might be going wrong:

There were 50 or more warnings (use warnings() to see the first 50)
Loading tumour files from /home/jgockley/UMAS_Project_B/WGS/TitanCNA/TMI40424/Chr22_Tumor
Loading BX counts from /home/jgockley/UMAS_Project_B/WGS/TitanCNA/TMI40424/Chr22_Tumor
/home/jgockley/UMAS_Project_B/WGS/TitanCNA/TMI40424/Chr22_Tumor/TMI40424_Tumor.10kb.bxTile.chr22.bed
Read 1016370 rows and 4 (of 4) columns from 0.874 GB file in 00:00:26
Reading GC and mappability files
Slurping: hg38_gc50V3.wig
Parsing: fixedStep chrom=1 start=1 step=50 span=50
Parsing: fixedStep chrom=10 start=1 step=50 span=50
Parsing: fixedStep chrom=11 start=1 step=50 span=50
Parsing: fixedStep chrom=12 start=1 step=50 span=50
Parsing: fixedStep chrom=13 start=1 step=50 span=50
Parsing: fixedStep chrom=14 start=1 step=50 span=50
Parsing: fixedStep chrom=15 start=1 step=50 span=50
Parsing: fixedStep chrom=16 start=1 step=50 span=50
Parsing: fixedStep chrom=17 start=1 step=50 span=50
Parsing: fixedStep chrom=18 start=1 step=50 span=50
Parsing: fixedStep chrom=19 start=1 step=50 span=50
Parsing: fixedStep chrom=2 start=1 step=50 span=50
Parsing: fixedStep chrom=20 start=1 step=50 span=50
Parsing: fixedStep chrom=21 start=1 step=50 span=50
Parsing: fixedStep chrom=22 start=1 step=50 span=50
Parsing: fixedStep chrom=3 start=1 step=50 span=50
Parsing: fixedStep chrom=4 start=1 step=50 span=50
Parsing: fixedStep chrom=5 start=1 step=50 span=50
Parsing: fixedStep chrom=6 start=1 step=50 span=50
Parsing: fixedStep chrom=7 start=1 step=50 span=50
Parsing: fixedStep chrom=8 start=1 step=50 span=50
Parsing: fixedStep chrom=9 start=1 step=50 span=50
Parsing: fixedStep chrom=X start=1 step=50 span=50
Parsing: fixedStep chrom=Y start=1 step=50 span=50
Sorting by decreasing chromosome size
No mappability wig file input, excluding from correction
Correcting Tumour
Loading required package: GenomeInfoDb
Removed 78001 bins near centromeres.
Applying filter on data...
Correcting for GC bias...
Error in predLoess(object$y, object$x, newx = if (is.null(newdata)) object$x else if (is.data.frame(newdata)) as.matrix(model.frame(delete.response(terms(object)),  :
  NA/NaN/Inf in foreign function call (arg 5)
Calls: loadReadCountsFromWig ... eval -> eval -> predict -> predict.loess -> predLoess
In addition: There were 21 warnings (use warnings() to see them)
Execution halted

**Comment by gavinha** [comment]
HI Jake,

It looks like there are NA values in the read count data.table object that was not properly removed within the `loadReadCountsFromWig` function. Or there are not enough data points in the data.table after filtering for extremely low and high coverage (see function below)
https://github.com/broadinstitute/ichorCNA/blob/91264fdc739f519d68cff9a9c6a18f32e410e3ab/R/utils.R#L207

I'm not sure but it may have to do with the small 50bp bin sizes. 

Best,
Gavin
