### ISSUE TITLE
fwdBack error

### ISSUE THREAD

**Issue by wyleung** [gavinha/TitanCNA#2]
I'm running TitanCNA v1.4.0 and have the following issue:

```
>
> convergeParams <- runEMclonalCN(workdata,gParams=params$genotypeParams,nParams=params$normalParams,
+                                 pParams=params$ploidyParams,sParams=params$cellPrevParams,
+                                 maxiter=20,maxiterUpdate=1500,txnExpLen=1e15,txnZstrength=1e5,
+                                 useOutlierState=FALSE,
+                                 normalEstimateMethod="map",estimateS=TRUE,estimatePloidy=TRUE)
titan: Running HMM...
fwdBack: Iteration 1 chr: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 24 *** Error in `/usr/local/R/R-3.1.1/lib/R/bin/exec/R': free(): invalid next size (fast): 0x0000000003a5c8a0 ***
```

How can I solve this issue? I'm working with UCSC style chromosome names.

**Comment by gavinha** [comment]
Hi wyleung,

The best way to receive support for TitanCNA is to use the Google Groups 
https://groups.google.com/forum/#!forum/titancna

With regards to your error... there appears to be a problem with the included chromosomes when running runEMclonalCN.  You should double check that you have not filtered out too much data when calling filterData().

Best,
Gavin

**Comment by wyleung** [comment]
Thanks, i'll post on the google forum with some examples and code.
