### ISSUE TITLE
getPositionOverlap function

### ISSUE THREAD

**Issue by lijinsgithub** [gavinha/TitanCNA#21]
Hello Gavin,

I am following your tutorial but got into a trouble from the very beginning step.
Would you mind to take a closer look at "getPositionOverlap" function? 
I installed this package a few weeks ago.

Thank you for your help.
Lijin

> logR <- getPositionOverlap(chr=data$chr, posn=data$posn, dataVal=cnData) 
> head(logR)
[1] NA NA NA NA NA NA
> tail(logR)
[1] NA NA NA NA NA NA
>

**Comment by gavinha** [comment]
Hi Lijin,

Are you wondering if the function is returning all NA values?  First, can you check this by seeing if the entire array is NA?
```
sum(is.na(logR))
```
If this is the case, then we need to see if `data` and `cnData` is compatible.  If you can provide the first few lines of both, that would be helpful for debugging.

Best,
Gavin

**Comment by lijinsgithub** [comment]
Gavin,

Thank you very much for you incredibly fast response!
I am attaching my log and the data files that I used (they are provided in
ext-data folder).
I will let you know after testing the same function with my data.

I believe using your built-in can be faster than my naive fixer with two
"for" loops.
Thanks again.

ps. I found that the data files are too big to attach. I simply used the
files in "extdata" folder.

Bests,
Lijin

**Comment by gavinha** [comment]
Hi Lijin,

You set `data` to use the UCSC chromosome naming convention
>`data$chr <- setGenomeStyle(data$chr, genomeStyle = "UCSC")`

However, `cnData` is set to use the NCBI chromosome naming convention. This is why did could not find any overlap.
>`cnData <- correctReadDepth(tumWig, normWig, gc, map, genomeStyle = "NCBI")`

Hope this helps.
Best,
Gavin

**Comment by gavinha** [comment]
I also want to point out that I provide a full R script to run the TITAN analysis
[https://github.com/gavinha/TitanCNA/tree/master/scripts/R_scripts](https://github.com/gavinha/TitanCNA/tree/master/scripts/R_scripts)

There is also a snakemake workflow that will start from BAM files and run all the steps necessary to generate the final TITAN results.
[https://github.com/gavinha/TitanCNA/tree/master/scripts/snakemake](https://github.com/gavinha/TitanCNA/tree/master/scripts/snakemake)

**Comment by lijinsgithub** [comment]
It was my simple mistake!

One last question, do you recommend to use snakemake over the old way using mappability and gccount wig files?  If so, what would be the main improvement?

Thank you very much for your help and kind response!

**Comment by gavinha** [comment]
The snakemake workflow includes the same GC and mappability correction.  My hope is that the snakemake will be an easy one-stop solution to combine all the steps into one workflow.

**Comment by lijinsgithub** [comment]
I will test snakelike and leave my comment which way, old vs new snakelike, would be easer for a beginner like me in few weeks!
Thanks again.
