### ISSUE TITLE
getSubcloneProfiles error

### ISSUE THREAD

**Issue by gavinha** [gavinha/TitanCNA#22]
Error in data.table(Subclone1 = subc1) : object 'subc1' not found
Calls: outputTitanResults ... eval -> eval -> eval -> getSubcloneProfiles -> data.table

This is likely related to an incompatible solution (i.e. ploidy and number of clusters). I will put in a few checks to allow it to complete.

**Comment by kcibul** [comment]
hi gavin -- I'm getting this error on ~30% of my samples (WGS+FFPE), wondering if there is a fix on the way or if there's a way to work around it.

**Comment by gavinha** [comment]
Hi @kcibul 

Thanks for bringing up issue again.  The error occurs in a post-processing step that looks at the clonal clusters but runs into a problem when there are no CNA calls (i.e. all copy neutral), likely due to noisy log ratio profiles.  

For FFPE samples, you should use a different pre-processing pipeline beyond just the GC/mappability correction in the TitanCNA pipeline.  I'm sure you've already considered using a panel of normals (e.g. ReCapSeg) approach.

Best,
Gavin
