### ISSUE TITLE
runTitanCNA and selectSolution error

### ISSUE THREAD

**Issue by elifirem** [gavinha/TitanCNA#24]
Hi, 
I am trying to run titanCNA on matched tumor-normal WES samples. I am following snakemake workflow but I am also running it inside of a HPC cloud. I downloaded both titanCNA and ichorCNA. 
-My first question is does the parameters of both config files (titan and ichor) need to be matched? I know titan snakefile invokes the others but in titan config file there is still a path for ichor script and libdir so I thought it migth affect. 
-When I changed the binsize from 10.000 to 100.000 or 1.000.000 the workflow gives error on earlier stages of the jobs. When I keep it at 10.00 I still get an error at runTitanCNA which is:

```
Error in job runTitanCNA while creating output files results/titan/hmm/titanCNA_ploidy2/RTF8_D_cluster2/, results/titan/hmm/titanCNA_ploidy2/RTF8_D_cluster2.titan.txt, results/titan/hmm/titanCNA_ploidy2/RTF8_D_cluster2.params.txt, results/titan/hmm/titanCNA_ploidy2/RTF8_D_cluster2.segs.txt, results/titan/hmm/titanCNA_ploidy2/RTF8_D_cluster2.seg.
RuleException:
CalledProcessError in line 53 of /mnt/lustre/sarihae/HNSCC_WES/titanCNA/scripts/snakemake/TitanCNA.snakefile: returned non-zero exit status 1.
  File "/mnt/lustre/sarihae/HNSCC_WES/titanCNA/scripts/snakemake/TitanCNA.snakefile", line 53, in __rule_runTitanCNA
  File "/cm/shared/apps/python/3.6.2/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Removing output files of failed job runTitanCNA since they might be corrupted:
results/titan/hmm/titanCNA_ploidy2/RTF8_D_cluster2/
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
```

I looked at the config file and changed libdirs from `path/to/titanCNA/R/ path/to/ichorCNA-master/R/` to `path/to/titanCNA/ path/to/ichorCNA-master/` and now I get an error at selectSolution which looks like:

```
Error in job selectSolution while creating output file results/titan/hmm/optimalClusterSolution.txt.
RuleException:
CalledProcessError in line 70 of /mnt/lustre/sarihae/HNSCC_WES/titanCNA/scripts/snakemake/TitanCNA.snakefile: returned non-zero exit status 2.
  File "/mnt/lustre/sarihae/HNSCC_WES/titanCNA/scripts/snakemake/TitanCNA.snakefile", line 70, in __rule_selectSolution
  File "/cm/shared/apps/python/3.6.2/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
```
What would you think it's causing my problem, is it related to input parameters, or sth else? I'd really appreciate any kind of help and guidance cause I am a little bit confused with this workflow.
Thanks in advance,
Irem

**Comment by gavinha** [comment]
Hi @elifirem 
Sorry for the delay and thanks for your interest in TITAN.

1) The parameters in the config files should be matched.  I still need to update the snakemake pipeline to simplify setting those parameters.

2) The error messages that you pasted are the default ones output by snakemake.  You will need to go into the `logs/` folder and look at the output there to see the actual error.
My guess is that one of the solutions failed to run although it is hard to tell what the cause is.  Can you please post what you find?  

3) Apologies for the `libdirs` settings. For TitanCNA, you do not need to include `R` but for ichorCNA you do.  It's a bit confusing because we constantly update both repos without making the snakemake consistent between the 2.
Also, you do not need to use `libdirs` at all as long as you have both ichorCNA and TitanCNA installed in R.  That parameter setting is there if you decide to change any underlying R code and would like to source that for your run instead.

Sorry again for the delay in responding. 

Best,
Gavin

**Comment by elifirem** [comment]
Hi Gavin,

Thank you so much for your response. This is a great tool but so much to discover. I actually made it to work, I realized bin size error was happening because I wasn't using different bin sized wig files but simply using the ones you provide. For the final error I posted, I saw that even though I had set `maxPloidy=3` in config files, titanCNA.snakefile was somehow not expanding ploidyRun3 dirs but only ploidyRun2. At line 83 `Rscript {params.solutionRscript} --ploidyRun2 {input.ploidyDirs[0]} --ploidyRun3 results/titan/hmm/titanCNA_ploidy3/ --threshold {params.threshold} --outFile {output} > {log} 2> {log}` when I added the plodiyRun3 directory manually, it worked. I did want to include `libdirs` as I was not running locally but in a cluster.

If you don't mind I will ask some more questions as I am not so sure about the results. I set maxPloidy at 3 as tumors might have higher. My optimalClusterSolution shows I even have some samples with ploidy 6. I guess that's expected? 

I also set maxNumClonalClusters: 2 for beginning. If the optimalClusterSolution is cluster 2, that sample has two values in cellPrev column. cellPrev is 1 for every sample if the solution is cluster 1 which I'd expect to be lower actually. If it has two values, the second one is usually around 0.8. Is this the reason to run titan multiple times with different number of clusters? If I just set it to 5 clusters wouldn't it still pick the optimal one? Sorry if I sound confusing. 

And finally, I wanted to find CNA results inside the files and as far as I could see `results/titan/hmm/sample_clusterX.segs.txt` had them, but the segments were very large (Around 30 per sample). Am I looking at the right files or do you have any recommendations for that? 

Thanks!
Irem

**Comment by elifirem** [comment]
An addition to my previous question;
The estimated ploidy numbers in optimalSolution for different runs with parameters set to ploidy(2,3) or ploidy(2,3,4) are quite different. How can I select which ones are better estimates? Again by looking at sdbw index values?

**Comment by gavinha** [comment]
Hi @elifirem 
The `segs.txt` files contain a good amount of information to interpret the results. The number of segments can vary depending on your tumor type, but it could also be a data/noise issue with segmentation.  

The best way to select the optimal solutions is to use the `selectSolutions.R` script. It is run as the last step in the snakemake pipeline.

To explain the cellular prevalence and cluster number interpretation.  Let's say you have a cluster02 solution selected as the optimal solution. This means that the first cluster (ie. clust=1) is always the "clonal" cluster.  That is, all CNA events in this cluster will have a cellular prevalence of 1.0 or 100%. This is true for any cluster0X solution. The 2nd cluster (clust=2) in this solution is the "subclonal" cluster and the cellular prevalence should be less than 1.0. 

Hope this helps,
Gavin

**Comment by pchamely** [comment]
Yes that does help! Thank you Gavin :). 

I was able to find all the necessary paths for the files in the config.yaml however, I'm having trouble locating snpDB: /path/to/hapmap_3.3.b37.vcf. Which package/library is this script a part of? 

Also should gc_hg19_10kb.wig instead be gc_hg19_1000kb.wig and map_hg19_10kb.wig be map_hg19_1000kb.wig?

Best,
Paulina
