### ISSUE TITLE
error running snakemake -s TitanCNA.snakefile -np

### ISSUE THREAD

**Issue by pchamely** [gavinha/TitanCNA#26]
Hi there,

I've git clone's TitanCNA and updated my samples.yaml to reflect the samples I'll be using however, when trying to run through the snakemake I get this error from the first step:

**Terminal command:**
snakemake -s TitanCNA.snakefile -np

**Output:**
SyntaxError:
Not all output, log and benchmark files of rule read_counter contain the same wildcards. This is crucial though, in order to avoid that two or more jobs write to the same file.
  File "/home/pchamely/TitanCNA/scripts/snakemake/TitanCNA.snakefile", line 4, in <module>
  File "/home/pchamely/TitanCNA/scripts/snakemake/ichorCNA.snakefile", line 25, in <module>

This is my first time using snakemake so I'm not sure what this means and was wondering if you could walk me through it?

**Comment by gavinha** [comment]
Hi @pchamely 

I have not encountered this before.  What version of snakemake are you using?

Can you also try using this command and see if the same error comes up again?

`snakemake -s ichorCNA.snakefile -np`

Thanks,
Gavin

**Comment by pchamely** [comment]
Hi Gavin,

When I run snakemake -s ichorCNA.snakefile -np I do get the same error. I'm not sure how to check the version of my snakemake but I'm using it as a package of python/3.6.0

**Comment by pchamely** [comment]
Hi Gavin,

I made the same revision to my ichorCNA.snakemake file as you did in the above commit and it seems to have fixed some things, however I'm getting a new error now:

**Input:**
snakemake -s TitanCNA.snakefile -np

**Output:**
Building DAG of jobs...
ChildIOException:
File/directory is a child to another output:
/home/pchamely/tools/TitanCNA/scripts/snakemake/results/ichorCNA/tumor_sample_1
/home/pchamely/tools/TitanCNA/scripts/snakemake/results/ichorCNA/tumor_sample_1/tumor_sample_1.cna.seg

**Comment by gavinha** [comment]
Hi @pchamely 

My version of snakemake (3.12.0) is older than the one you are using.  I haven't updated in a while.  The new version seems to make important checks to the snakefile. I will need to update everything to the latest version and test it.  This will take some time.  

If you need to perform this analysis right away, perhaps try v3.12.0 of snakemake in the meantime?

Thanks,
Gavin

**Comment by pchamely** [comment]
Hi Gavin,

Sounds good! I will try it with that version and thank you for the help :). 

Was the commit that you made above something that did need to change in my ichorCNA.snakefile or should I revert to the original version now that I'm using an older version of snakemake?

Thanks!

**Comment by pchamely** [comment]
Hi Gavin,

I tried the analysis on v3.12.0 of snakemake but still getting the error:
Building DAG of jobs...
ChildIOException:
File/directory is a child to another output:
/home/pchamely/tools/TitanCNA/scripts/snakemake/results/ichorCNA/tumor_sample_1
/home/pchamely/tools/TitanCNA/scripts/snakemake/results/ichorCNA/tumor_sample_1/tumor_sample_1.cna.seg

Here are all of the software package versions that I'm using, let me know if any of these could be causing the problem:

**R-3.4.1**
TitanCNA - ‘1.16.0’
ichorCNA - '0.1.0’
HMMcopy - ‘1.20.0’
optparse - ‘1.6.1.2’
stringr - ‘1.3.1’
SNPchip - ‘2.24.0’

**Python-3.4.9**
snakemake - '3.12.0'
PySAM - '0.11.2.1'
PyYAML- '3.12'

**samtools-1.7**
**bcftools - 1.7**
**HMM_Copy_Utils -1.0**

**Comment by gavinha** [comment]
Try commenting out this line using `#`

https://github.com/gavinha/TitanCNA/blob/1682cf421b937aed8c38351b770a38c9cf1414fd/scripts/snakemake/ichorCNA.snakefile#L34

**Comment by pchamely** [comment]
Hi Gavin,

Thank you so much for all the help and sorry for all the trouble! That works now :)!

**Comment by pchamely** [comment]
Hey Gavin,

So, snakemake -s TitanCNA.snakefile -np ran fine will no errors, however when I try to run the workflow with snakemake -s TitanCNA.snakefile --cores 5, I get this error 

[E::fai_build3] Failed to open the FASTA file /seq/references/Homo_sapiens_assembly19/v1/Homo_sapiens_assembly19.fasta

and this is then followed by other errors, which I think probably stemmed from this first issue.

I then looked into the log files and the only one that had any text was TitanCNA/scripts/snakemake/logs/readDepth and the error was:

/bin/bash: /path/to/readCounter: No such file or directory.

Does this mean there is an issue with my HMMcopy Suite? If so why would that be if am loading HMM_Copy_Utils/1.0.?

Thanks,
Paulina

**Comment by gavinha** [comment]
Hi @pchamely 

You need to modify `config.yaml` so that the file paths exists. For example, the `readCounter` executable is required to run the read depth analysis. You need to provide the path to this file in `config.yaml`.

Best,
Gavin

**Comment by pchamely** [comment]
Yes that does help! Thank you Gavin :).

I was able to find all the necessary paths for the files in the config.yaml however, I'm having trouble locating snpDB: /path/to/hapmap_3.3.b37.vcf. Which package/library is this script a part of?

Also should gc_hg19_10kb.wig instead be gc_hg19_1000kb.wig and map_hg19_10kb.wig be map_hg19_1000kb.wig?

Best,
Paulina
