### ISSUE TITLE
TITAN and phyloWGS (getting majorCN and minorCN)

### ISSUE THREAD

**Issue by pchamely** [gavinha/TitanCNA#27]
Hi Gavin,

I was able to successfully run TITAN on my BAM files, however, I am trying to run the CNV information through phyloWGS (which says that it is compatible with titan's cnv file format), but it says that my input cnv file should include the following fields: 
chromosome
Start_Position
End_Position
MajorCN
MinorCN

I saw in the documentation of the R package that by doing 

> segs <- outputTitanSegments(results, id = "test", convergeParams, filename = NULL, igvfilename = NULL)
> head(segs)

you can get a output with the following sections:
1. Sample: Name of sample
2. Chromosome, Start_Position.bp., End_Position.bp.: Coordinates of segment 3. Length.snps.: Number of SNPs in the segment
4. Median_Ratio: Median allelic ratio across SNPs in the segment
5. Median_logR: Median log ratio across SNPs in the segment
6. TITAN_state, TITAN_call, Copy_Number: Same as defined above
7. MinorCN: Copy number of minor allele
8. MajorCN: Copy number of major allele
9. Clonal_Cluster, Cellular_Frequency: Same as defined above

From running the snakemake I found some output files that had the Chr,  start, end and copy.number (specifically my tumor_sample_1.seg file in the results/ichorCNA/sample1 folder) however, I can't seem to find them in any of my output files with MinorCN or MajorCN. I've never used R before and was wondering if this was the only way to get this output or if I can get it from the snakemake output?   

Thanks,
Paulina

**Comment by pchamely** [comment]
Hi Gavin,

I just realized that I'm missing the output file titan/hmm entirely... is the output that I'm looking for usually in this folder?

- Paulina

**Comment by gavinha** [comment]
Hi @pchamely 

The output file you are looking for should have the extension `*segs.txt`. If the snakemake job for the `runTitanCNA` rule failed, it's possible that it removed the file as part of making sure the failed run is wiped. 

What files do you see in the `results` directory for one specific sample?

**Comment by pchamely** [comment]
Hi Gavin,

I did get some seg.txt files but they weren't what I was looking for. I also realized that there was an error when running titan as I hadn't added the data.table and doMC packages to my R. I'm going to run everything through again as I'm guessing that might be the issue

In terms of the results I got so far, for one sample (tumor_sample_1), I'm seeing:

**titan/tumorCounts:**
tumor_sample_1.tumCounts.txt
tumor_sample_1.tumCounts.chr*.txt (with one of these for each  chromosome)

**titan/hetPosns:**
tumor_sample_1.chr*.vcf (with one of these for each chromosome)

**readDepth:**
tumor_sample_1.bin10000.wig

**ichorCNA:**
tumor_sample_1.correctedDepth.txt  tumor_sample_1.RData  
tumor_sample_1.seg.txt
tumor_sample_1.cna.seg  
tumor_sample_1.params.txt          
tumor_sample_1.seg
tumor_sample_1_bias.png       
tumor_sample_1_CNA_chr*.png  (one fro each chromosome) 
tumor_sample_1_correct.png
tumor_sample_1_genomeWide_all_sols.pdf
tumor_sample_1_genomeWide_n0.5-p2.png
tumor_sample_1_genomeWide_n0.5-p3.png
tumor_sample_1_genomeWide.png
tumor_sample_1_tpdf.pdf

**Comment by gavinha** [comment]
The files that you'll want will be under `titan/hmm/`. Because runTitanCNA jobs failed, this directory and the output files were not generated.

**Comment by pchamely** [comment]
Perfect and thank you for all the help and speedy responses you were extremely helpful!

I was also wondering why the Y chromosome is excluded from all of the analyses, was this intentional or it that something I should change?

**Comment by gavinha** [comment]
Hi @pchamely 

Excluding chrY is intentional.

Best,
Gavin
