### ISSUE TITLE
choosing maxCN value

### ISSUE THREAD

**Issue by pchamely** [gavinha/TitanCNA#28]
Hi Gavin,

I had a general question about TitanCNA, I saw that there is a maxCN value under 'ichorCNA_maxCN' and this has a default value of 8. For the tumor sample that I'm working with, I know that the CN's can be up to 100 but I am not sure what the maxCN value would be. I saw that the newest version of TitanCNA has the function correctIntegerCN(). Does the new function correctIntegerCN() take care of this issue of not knowing what your maxNC should be and does it simply replace the maxCN when it is higher than inputed value? 

I also read that this new function re-calculates the CN by "correcting log ratio based on purity and ploidy and then convert to decimal CN value" and so are the purity and ploidy also values that I should be specifying myself (since the CN value is calculated off of that) or are these also estimated?

Thanks,
Paulina

**Comment by gavinha** [comment]
Hi @pchamely 

Yes, `correctIntegerCN()` should take care of the extremely high-level copy number events. You do not need to do anything different. The purity and ploidy used for the integer CN adjustment is done based on the estimated values. Also, you can continue to use `maxCN 8`.

Hope this helps.
Best,
Gavin
