### ISSUE TITLE
Where to download v1.5.8

### ISSUE THREAD

**Issue by amohajeri** [gavinha/TitanCNA#3]
Hello,

I need to download TitanCNA 1.5.8 to use it with Titanrunner pipeline. I couldn't find a link to download this version. Is it available for download?

Thank you

**Comment by gavinha** [comment]
Hi,

You can download TitanCNA v1.7.1.  It is the same as v1.5.8.  The version bump is to keep consistent with Bioconductor's SVN-github bridge.

You can find this under "Releases"
 https://github.com/gavinha/TitanCNA/releases/tag/v1.7.1

**Comment by artonmarton** [comment]
Hi Gavin, Thanks. This is helpful. I have the TITANRunner installed already
but it is an older version (v0.1.1). Can I update the TITANRunner
using TitanCNA v1.7.1 or is this only for using the R script?

On Dec 14, 2015, at 9:36 PM, Gavin Ha <notifications@github.com> wrote:

Reply to this email directly or view it on GitHub
<https://github.com/gavinha/TitanCNA/issues/3#issuecomment-164649358>.
