### ISSUE TITLE
cytobandFile error

### ISSUE THREAD

**Issue by elifirem** [gavinha/TitanCNA#36]
Hi, 
I was able to run TitanCNA succesfully before. Now when I try to run with hg19 aligned samples, it gives error at rule runTitanCNA step;

`Error in job runTitanCNA while creating output files ...
RuleException: CalledProcessError in line 54 of /TitanCNAmaster/scripts/snakemake/TitanCNA.snakefile:`

and the log files say;
`Error in fread(cytobandFile) : object 'cytobandFile' not found`

It says cytobandFile is only needed if ref.genome is hg38. I don't know how to get around this error. Any help would be much appreciated. Thanks!

Irem

**Comment by gavinha** [comment]
Hi @elifirem 

Can you please show me lines 14 to 19 from the [config.yaml](https://github.com/gavinha/TitanCNA/blob/master/scripts/snakemake/config/config.yaml) file?

In the `titanCNA.R` script, the line that your error occurs on is here.  There is a check to see if you are using `hg38` and that the `cytobandFile` exists. 
https://github.com/gavinha/TitanCNA/blob/7a9fa7c14f196f8f5eb91e6dcaa6a1de85de065d/scripts/R_scripts/titanCNA.R#L287-L291

-Gavin
