### ISSUE TITLE
computeSDbwIndex correct?

### ISSUE THREAD

**Issue by alashkov83** [gavinha/TitanCNA#43]
In file https://github.com/gavinha/TitanCNA/blob/master/R/utils.R
in function computeSDbwIndex code:

```r
else if (S_Dbw.method == "Tong"){
			###### NOTE #######
			## The authors originally used ((N-ni)/N), but this is incorrect ##
			## We want a weighted-sum ##
			scat.Ci[i] <- ((ni) / N) * (var.Ci/var.D)
```
Are your sure? 

In paper (Youngok Kim and Soowon Lee. A clustering validity assessment Index., 2003,, 602–608):

If two clusters have the same variance but different numbers of tuples, the variance
of cluster with more tuples has more effect on the scatter function than the one with
less tuples. By minimizing the influence of small clusters or noisy clusters, Scat* can
be more robust than Scat of S_Dbw index.

Alexander Lashkov

**Comment by gavinha** [comment]
Hi @alashkov83 

Thank you for bringing this up. My intention was to penalize smaller clusters by weighting the `scat` term. However, it seems that the current code is doing the opposite.  I will change it back to `((N-ni)/N)` and test it. 
Over the years, I have added in other post-processing steps to prune out small clusters, etc.  However, this bug is a very good catch and should definitely be fixed.

Thanks again.
Gavin

**Comment by fpbarthel** [comment]
@gavinha thanks for the fix! I'm not 100% sure about the correctness, but I have two related tumor samples from the same patient and the selected solutions for each of two look very different. Compare 1 (2 clusters) and 2a (3 clusters) below. I believe 2b (2 clusters) to be the correct solution even though it has a higher S_Dbw than 2a.

# 1
Selected solution

![screen shot 2018-11-29 at 5 33 08 pm](https://user-images.githubusercontent.com/9220167/49256487-2fdba780-f3fd-11e8-9a31-23c8b1f56fe1.png)

![screen shot 2018-11-29 at 5 33 01 pm](https://user-images.githubusercontent.com/9220167/49256491-323e0180-f3fd-11e8-936b-23f78ba9ded1.png)

```
Normal contamination estimate:	0.08729
Average tumour ploidy estimate:	1.959
Clonal cluster cellular prevalence Z=1:	1
AllelicRatio binomial means for clonal cluster Z=1:	0.5 0.9197 0.9564 0.5548 0.97 0.6567 0.9772 0.7386 0.5573 0.9816 0.7889 0.5963 0.9846 0.823 0.6615 0.5581 0.9867 0.8476 0.7086 0.5695 0.9883 0.8662 0.7442 0.6221 0.5586
logRatio Gaussian means for clonal cluster Z=1:	-3.491 -0.8519 0.02732 0.02732 0.5697 0.5697 0.9629 0.9629 0.9629 1.272 1.272 1.272 1.526 1.526 1.526 1.526 1.742 1.742 1.742 1.742 1.93 1.93 1.93 1.93 1.93
logRatio Gaussian variance:	0.009996 0.01092 0.00847 0.00847 0.01013 0.01013 0.01101 0.01101 0.01101 0.009996 0.009996 0.009996 0.009996 0.009996 0.009996 0.009996 0.009996 0.009996 0.009996 0.009996 0.01052 0.01052 0.01052 0.01052 0.01052
Number of iterations:	5
Log likelihood:	-41400
S_Dbw dens.bw (LogRatio):	0.0389 
S_Dbw scat (LogRatio):	0.0398 
S_Dbw validity index (LogRatio):	0.0787 
S_Dbw dens.bw (AllelicRatio):	0.1918 
S_Dbw scat (AllelicRatio):	0.0206 
S_Dbw validity index (AllelicRatio):	0.2124 
S_Dbw dens.bw (Both):	0.2308 
S_Dbw scat (Both):	0.0604 
S_Dbw validity index (Both):	0.2911 
```

## 2a
Selected solution because it has lower `S_Dbw` compared to **2b**

![screen shot 2018-11-29 at 5 32 05 pm](https://user-images.githubusercontent.com/9220167/49256357-bcd23100-f3fc-11e8-92ac-b1a4100aeb31.png)

![screen shot 2018-11-29 at 5 31 59 pm](https://user-images.githubusercontent.com/9220167/49256360-bf348b00-f3fc-11e8-92f1-263a7078ce6b.png)

```
Normal contamination estimate:	0.456
Average tumour ploidy estimate:	1.882
Clonal cluster cellular prevalence Z=2:	1 0.5611
AllelicRatio binomial means for clonal cluster Z=1:	0.5 0.6868 0.772 0.5314 0.8208 0.6069 0.8523 0.6762 0.5407 0.8745 0.7247 0.5749 0.8908 0.7605 0.6303 0.5451 0.9034 0.7881 0.6729 0.5576 0.9134 0.81 0.7067 0.6033 0.5477
logRatio Gaussian means for clonal cluster Z=1:	-1.086 -0.411 0.04702 0.04702 0.3941 0.3941 0.6737 0.6737 0.6737 0.9078 0.9078 0.9078 1.109 1.109 1.109 1.109 1.286 1.286 1.286 1.286 1.443 1.443 1.443 1.443 1.443
AllelicRatio binomial means for clonal cluster Z=2:	0.5 0.5901 0.6526 0.5176 0.6986 0.5662 0.7339 0.6169 0.527 0.7617 0.657 0.5523 0.7843 0.6895 0.5948 0.5328 0.803 0.7164 0.6299 0.5433 0.8187 0.739 0.6593 0.5797 0.5368
logRatio Gaussian means for clonal cluster Z=2:	-0.4785 -0.1919 0.04702 0.04702 0.252 0.252 0.4314 0.4314 0.4314 0.5909 0.5909 0.5909 0.7346 0.7346 0.7346 0.7346 0.8652 0.8652 0.8652 0.8652 0.985 0.985 0.985 0.985 0.985
logRatio Gaussian variance:	0.009972 0.01002 0.008973 0.008973 0.01017 0.01017 0.009907 0.009907 0.009907 0.0102 0.0102 0.0102 0.009993 0.009993 0.009993 0.009993 0.009996 0.009996 0.009996 0.009996 0.01005 0.01005 0.01005 0.01005 0.01005
Number of iterations:	5
Log likelihood:	-35860
S_Dbw dens.bw (LogRatio):	0.1628 
S_Dbw scat (LogRatio):	0.0436 
S_Dbw validity index (LogRatio):	0.2064 
S_Dbw dens.bw (AllelicRatio):	0.3962 
S_Dbw scat (AllelicRatio):	0.0431 
S_Dbw validity index (AllelicRatio):	0.4393 
S_Dbw dens.bw (Both):	0.5590 
S_Dbw scat (Both):	0.0867 
S_Dbw validity index (Both):	0.6457 
```

## 2b
My personal preferred solution because it looks better and more similar to related sample **1**. `S_Dbw` is higher compared to **2a**.

![screen shot 2018-11-29 at 5 40 30 pm](https://user-images.githubusercontent.com/9220167/49256713-f0618b00-f3fd-11e8-970b-831a21f5223c.png)

![screen shot 2018-11-29 at 5 40 41 pm](https://user-images.githubusercontent.com/9220167/49256717-f35c7b80-f3fd-11e8-8d62-57d75996d0bf.png)

```
Normal contamination estimate:	0.425
Average tumour ploidy estimate:	1.863
Clonal cluster cellular prevalence Z=2:	1 0.6026
AllelicRatio binomial means for clonal cluster Z=1:	0.5 0.7018 0.7875 0.5332 0.835 0.6117 0.8651 0.6825 0.5421 0.8859 0.7315 0.5772 0.9012 0.7674 0.6337 0.5463 0.9128 0.7949 0.6769 0.559 0.922 0.8165 0.711 0.6055 0.5487
logRatio Gaussian means for clonal cluster Z=1:	-1.177 -0.4313 0.05778 0.05778 0.4224 0.4224 0.7132 0.7132 0.7132 0.955 0.955 0.955 1.162 1.162 1.162 1.162 1.343 1.343 1.343 1.343 1.504 1.504 1.504 1.504 1.504
AllelicRatio binomial means for clonal cluster Z=2:	0.5 0.6048 0.6733 0.52 0.7215 0.5738 0.7574 0.6287 0.5297 0.785 0.671 0.557 0.807 0.7047 0.6023 0.5354 0.8249 0.7321 0.6393 0.5464 0.8398 0.7549 0.6699 0.585 0.5392
logRatio Gaussian means for clonal cluster Z=2:	-0.556 -0.2167 0.05778 0.05778 0.2883 0.2883 0.487 0.487 0.487 0.6617 0.6617 0.6617 0.8174 0.8174 0.8174 0.8174 0.958 0.958 0.958 0.958 1.086 1.086 1.086 1.086 1.086
logRatio Gaussian variance:	0.009981 0.01016 0.009034 0.009034 0.009998 0.009998 0.01006 0.01006 0.01006 0.009995 0.009995 0.009995 0.009976 0.009976 0.009976 0.009976 0.009996 0.009996 0.009996 0.009996 0.01015 0.01015 0.01015 0.01015 0.01015
Number of iterations:	5
Log likelihood:	-35610
S_Dbw dens.bw (LogRatio):	0.1202 
S_Dbw scat (LogRatio):	0.0426 
S_Dbw validity index (LogRatio):	0.1628 
S_Dbw dens.bw (AllelicRatio):	0.5091 
S_Dbw scat (AllelicRatio):	0.0419 
S_Dbw validity index (AllelicRatio):	0.5510 
S_Dbw dens.bw (Both):	0.6293 
S_Dbw scat (Both):	0.0845 
S_Dbw validity index (Both):	0.7137 
```

**Comment by gavinha** [comment]
@fpbarthel 

You are likely correct in that 2b should be the correct solution. 
For inspecting solutions based on number of clusters and clonality, the plot that is useful is the `CP.png` and also plots for each individual chromosome.  It appears there is a subclonal deletion of chr15 and hopefully the `CP` plots show this. 

2a was initialized at 3 clusters but ended up removing one of the clusters. Perhaps if this did not happen, then the SDbw of all 3 clusters will yield a higher value (and not be selected). This might be an example of my attempt to clean up near empty clusters doing more bad than good, and that this new `scat*` fix might help.  

**I haven't had the chance to test whether the new `scat*` and cluster-pruning post-processing should co-exist. So I may decide to remove the cluster-pruning step later on.**   

At the moment, this can be easily switched off in [titanCNA.R](https://github.com/gavinha/TitanCNA/blob/master/scripts/R_scripts/titanCNA.R)
https://github.com/gavinha/TitanCNA/blob/60408ca0949fe1203844f549e35ffff1127eba00/scripts/R_scripts/titanCNA.R#L277

where you will add the argument `correctResults = FALSE`.  
See the function arguments here:
https://github.com/gavinha/TitanCNA/blob/60408ca0949fe1203844f549e35ffff1127eba00/R/utils.R#L862-L865

**Comment by fpbarthel** [comment]
As always thanks for the great suggestions @gavinha !

I've updated my post to add the CP plots to show that indeed the subclonal deletion of chr15 is nicely shown.

I am currently running all my samples with the new `scat*` with cluster post-pruning turned **on** and will rerun all my samples with the new `scat*` and with cluster post-pruning turned **off**, compare and then post my findings for both here.

Floris

**Comment by fpbarthel** [comment]
It looks like although these changes have a dramatic effect on the `SDbw`, the `SDbw` values for the inferior 2a are consistently lower. It looks like this may be a case for manual review.

Here are some observations:
- Keeping the 3rd cluster in (2a) with correctResult = `FALSE` led to an expected increase in overall Sdbw
- Yet, even with correctResult = `FALSE`, the overall Sdbw in 2a < 2b
- The LogRatio SDbw is lower in 2b compared to 2a, but the AllelicRatio SDbw is higher
- The superior solution 2b has a slightly higher log likelihood with correctResults = `TRUE` (identical to the logliks in my post above) but without correction, the log likelihood is higher in the inferior solution 2a

## 2a, new `scat*` correctResults = `TRUE`

<img width="959" alt="screen shot 2018-11-30 at 7 52 18 am" src="https://user-images.githubusercontent.com/9220167/49290425-f0e93880-f474-11e8-9c0a-763c5728788f.png">

<img width="957" alt="screen shot 2018-11-30 at 7 52 29 am" src="https://user-images.githubusercontent.com/9220167/49290429-f34b9280-f474-11e8-91ca-d2f671961131.png">

<img width="993" alt="screen shot 2018-11-30 at 7 52 07 am" src="https://user-images.githubusercontent.com/9220167/49290435-f5155600-f474-11e8-9b35-8f5637dbebdb.png">

```
Normal contamination estimate:	0.456
Average tumour ploidy estimate:	1.882
Clonal cluster cellular prevalence Z=2:	1 0.5611
AllelicRatio binomial means for clonal cluster Z=1:	0.5 0.6868 0.772 0.5314 0.8208 0.6069 0.8523 0.6762 0.5407 0.8745 0.7247 0.5749 0.8908 0.7605 0.6303 0.5451 0.9034 0.7881 0.6729 0.5576 0.9134 0.81 0.7067 0.6033 0.5477
logRatio Gaussian means for clonal cluster Z=1:	-1.086 -0.411 0.04702 0.04702 0.3941 0.3941 0.6737 0.6737 0.6737 0.9078 0.9078 0.9078 1.109 1.109 1.109 1.109 1.286 1.286 1.286 1.286 1.443 1.443 1.443 1.443 1.443
AllelicRatio binomial means for clonal cluster Z=2:	0.5 0.5901 0.6526 0.5176 0.6986 0.5662 0.7339 0.6169 0.527 0.7617 0.657 0.5523 0.7843 0.6895 0.5948 0.5328 0.803 0.7164 0.6299 0.5433 0.8187 0.739 0.6593 0.5797 0.5368
logRatio Gaussian means for clonal cluster Z=2:	-0.4785 -0.1919 0.04702 0.04702 0.252 0.252 0.4314 0.4314 0.4314 0.5909 0.5909 0.5909 0.7346 0.7346 0.7346 0.7346 0.8652 0.8652 0.8652 0.8652 0.985 0.985 0.985 0.985 0.985
logRatio Gaussian variance:	0.009972 0.01002 0.008973 0.008973 0.01017 0.01017 0.009907 0.009907 0.009907 0.0102 0.0102 0.0102 0.009993 0.009993 0.009993 0.009993 0.009996 0.009996 0.009996 0.009996 0.01005 0.01005 0.01005 0.01005 0.01005
Number of iterations:	5
Log likelihood:	-35860
S_Dbw dens.bw (LogRatio):	0.1628 
S_Dbw scat (LogRatio):	0.3510 
S_Dbw validity index (LogRatio):	0.5138 
S_Dbw dens.bw (AllelicRatio):	0.3962 
S_Dbw scat (AllelicRatio):	0.9996 
S_Dbw validity index (AllelicRatio):	1.3958 
S_Dbw dens.bw (Both):	0.5590 
S_Dbw scat (Both):	1.3506 
S_Dbw validity index (Both):	1.9096 
```

## 2b, new `scat*` correctResults = `TRUE`

<img width="969" alt="screen shot 2018-11-30 at 7 53 41 am" src="https://user-images.githubusercontent.com/9220167/49290503-1ece7d00-f475-11e8-8cc8-9cf6e7f46277.png">

<img width="956" alt="screen shot 2018-11-30 at 7 53 54 am" src="https://user-images.githubusercontent.com/9220167/49290508-22620400-f475-11e8-99bc-3d2117c2d814.png">

<img width="996" alt="screen shot 2018-11-30 at 7 53 29 am" src="https://user-images.githubusercontent.com/9220167/49290513-24c45e00-f475-11e8-8c30-94aa4223fd0a.png">

```
Normal contamination estimate:	0.425
Average tumour ploidy estimate:	1.863
Clonal cluster cellular prevalence Z=2:	1 0.6026
AllelicRatio binomial means for clonal cluster Z=1:	0.5 0.7018 0.7875 0.5332 0.835 0.6117 0.8651 0.6825 0.5421 0.8859 0.7315 0.5772 0.9012 0.7674 0.6337 0.5463 0.9128 0.7949 0.6769 0.559 0.922 0.8165 0.711 0.6055 0.5487
logRatio Gaussian means for clonal cluster Z=1:	-1.177 -0.4313 0.05778 0.05778 0.4224 0.4224 0.7132 0.7132 0.7132 0.955 0.955 0.955 1.162 1.162 1.162 1.162 1.343 1.343 1.343 1.343 1.504 1.504 1.504 1.504 1.504
AllelicRatio binomial means for clonal cluster Z=2:	0.5 0.6048 0.6733 0.52 0.7215 0.5738 0.7574 0.6287 0.5297 0.785 0.671 0.557 0.807 0.7047 0.6023 0.5354 0.8249 0.7321 0.6393 0.5464 0.8398 0.7549 0.6699 0.585 0.5392
logRatio Gaussian means for clonal cluster Z=2:	-0.556 -0.2167 0.05778 0.05778 0.2883 0.2883 0.487 0.487 0.487 0.6617 0.6617 0.6617 0.8174 0.8174 0.8174 0.8174 0.958 0.958 0.958 0.958 1.086 1.086 1.086 1.086 1.086
logRatio Gaussian variance:	0.009981 0.01016 0.009034 0.009034 0.009998 0.009998 0.01006 0.01006 0.01006 0.009995 0.009995 0.009995 0.009976 0.009976 0.009976 0.009976 0.009996 0.009996 0.009996 0.009996 0.01015 0.01015 0.01015 0.01015 0.01015
Number of iterations:	5
Log likelihood:	-35610
S_Dbw dens.bw (LogRatio):	0.1202 
S_Dbw scat (LogRatio):	0.3131 
S_Dbw validity index (LogRatio):	0.4333 
S_Dbw dens.bw (AllelicRatio):	0.5091 
S_Dbw scat (AllelicRatio):	1.1279 
S_Dbw validity index (AllelicRatio):	1.6370 
S_Dbw dens.bw (Both):	0.6293 
S_Dbw scat (Both):	1.4410 
S_Dbw validity index (Both):	2.0703 
```

## 2a, new `scat*` correctResults = `FALSE`

<img width="969" alt="screen shot 2018-11-30 at 7 42 09 am" src="https://user-images.githubusercontent.com/9220167/49290070-e67a6f00-f473-11e8-93da-b6876ee0b77b.png">

<img width="974" alt="screen shot 2018-11-30 at 7 42 23 am" src="https://user-images.githubusercontent.com/9220167/49290076-e8443280-f473-11e8-8342-166ed96bac5b.png">

<img width="996" alt="screen shot 2018-11-30 at 7 41 52 am" src="https://user-images.githubusercontent.com/9220167/49290083-ec705000-f473-11e8-9ac5-8b55ee1659c1.png">

```
Normal contamination estimate:	0.3521
Average tumour ploidy estimate:	1.882
Clonal cluster cellular prevalence Z=3:	0.976 0.8397 0.4712
AllelicRatio binomial means for clonal cluster Z=1:	0.5 0.6868 0.772 0.5314 0.8208 0.6069 0.8523 0.6762 0.5407 0.8745 0.7247 0.5749 0.8908 0.7605 0.6303 0.5451 0.9034 0.7881 0.6729 0.5576 0.9134 0.81 0.7067 0.6033 0.5477
logRatio Gaussian means for clonal cluster Z=1:	-1.077 -0.4018 0.05617 0.05617 0.4033 0.4033 0.6829 0.6829 0.6829 0.917 0.917 0.917 1.118 1.118 1.118 1.118 1.295 1.295 1.295 1.295 1.452 1.452 1.452 1.452 1.452
AllelicRatio binomial means for clonal cluster Z=2:	0.5 0.7312 0.8162 0.5365 0.8603 0.6201 0.8874 0.6937 0.5447 0.9057 0.7434 0.5811 0.9188 0.7792 0.6396 0.5483 0.9288 0.8063 0.6838 0.5613 0.9365 0.8274 0.7183 0.6091 0.5504
logRatio Gaussian means for clonal cluster Z=2:	-1.387 -0.4921 0.05617 0.05617 0.4525 0.4525 0.7631 0.7631 0.7631 1.019 1.019 1.019 1.235 1.235 1.235 1.235 1.424 1.424 1.424 1.424 1.591 1.591 1.591 1.591 1.591
AllelicRatio binomial means for clonal cluster Z=3:	0.5 0.5901 0.6526 0.5176 0.6986 0.5662 0.7339 0.6169 0.527 0.7617 0.657 0.5523 0.7843 0.6895 0.5948 0.5328 0.803 0.7164 0.6299 0.5433 0.8187 0.739 0.6593 0.5797 0.5368
logRatio Gaussian means for clonal cluster Z=3:	-0.4693 -0.1828 0.05617 0.05617 0.2611 0.2611 0.4405 0.4405 0.4405 0.6001 0.6001 0.6001 0.7437 0.7437 0.7437 0.7437 0.8744 0.8744 0.8744 0.8744 0.9941 0.9941 0.9941 0.9941 0.9941
logRatio Gaussian variance:	0.009972 0.01002 0.008973 0.008973 0.01017 0.01017 0.009907 0.009907 0.009907 0.0102 0.0102 0.0102 0.009993 0.009993 0.009993 0.009993 0.009996 0.009996 0.009996 0.009996 0.01005 0.01005 0.01005 0.01005 0.01005
Number of iterations:	5
Log likelihood:	-30770
S_Dbw dens.bw (LogRatio):	0.1860 
S_Dbw scat (LogRatio):	0.3804 
S_Dbw validity index (LogRatio):	0.5664 
S_Dbw dens.bw (AllelicRatio):	0.4345 
S_Dbw scat (AllelicRatio):	0.9837 
S_Dbw validity index (AllelicRatio):	1.4182 
S_Dbw dens.bw (Both):	0.6205 
S_Dbw scat (Both):	1.3641 
S_Dbw validity index (Both):	1.9846 
```

## 2b, new `scat*` correctResults = `FALSE`

<img width="974" alt="screen shot 2018-11-30 at 7 47 01 am" src="https://user-images.githubusercontent.com/9220167/49290148-30fbeb80-f474-11e8-8473-0a2d2542b217.png">

<img width="970" alt="screen shot 2018-11-30 at 7 47 13 am" src="https://user-images.githubusercontent.com/9220167/49290159-33f6dc00-f474-11e8-8160-54221ab0b0ff.png">

<img width="991" alt="screen shot 2018-11-30 at 7 46 51 am" src="https://user-images.githubusercontent.com/9220167/49290166-36f1cc80-f474-11e8-9816-39d397abcf26.png">

```
Normal contamination estimate:	0.4083
Average tumour ploidy estimate:	1.863
Clonal cluster cellular prevalence Z=2:	0.9718 0.5857
AllelicRatio binomial means for clonal cluster Z=1:	0.5 0.7018 0.7875 0.5332 0.835 0.6117 0.8651 0.6825 0.5421 0.8859 0.7315 0.5772 0.9012 0.7674 0.6337 0.5463 0.9128 0.7949 0.6769 0.559 0.922 0.8165 0.711 0.6055 0.5487
logRatio Gaussian means for clonal cluster Z=1:	-1.175 -0.4296 0.05949 0.05949 0.4241 0.4241 0.7149 0.7149 0.7149 0.9568 0.9568 0.9568 1.164 1.164 1.164 1.164 1.345 1.345 1.345 1.345 1.506 1.506 1.506 1.506 1.506
AllelicRatio binomial means for clonal cluster Z=2:	0.5 0.6048 0.6733 0.52 0.7215 0.5738 0.7574 0.6287 0.5297 0.785 0.671 0.557 0.807 0.7047 0.6023 0.5354 0.8249 0.7321 0.6393 0.5464 0.8398 0.7549 0.6699 0.585 0.5392
logRatio Gaussian means for clonal cluster Z=2:	-0.5543 -0.215 0.05949 0.05949 0.29 0.29 0.4887 0.4887 0.4887 0.6634 0.6634 0.6634 0.8191 0.8191 0.8191 0.8191 0.9597 0.9597 0.9597 0.9597 1.088 1.088 1.088 1.088 1.088
logRatio Gaussian variance:	0.009981 0.01016 0.009034 0.009034 0.009998 0.009998 0.01006 0.01006 0.01006 0.009995 0.009995 0.009995 0.009976 0.009976 0.009976 0.009976 0.009996 0.009996 0.009996 0.009996 0.01015 0.01015 0.01015 0.01015 0.01015
Number of iterations:	5
Log likelihood:	-31120
S_Dbw dens.bw (LogRatio):	0.1202 
S_Dbw scat (LogRatio):	0.3131 
S_Dbw validity index (LogRatio):	0.4333 
S_Dbw dens.bw (AllelicRatio):	0.5091 
S_Dbw scat (AllelicRatio):	1.1279 
S_Dbw validity index (AllelicRatio):	1.6370 
S_Dbw dens.bw (Both):	0.6293 
S_Dbw scat (Both):	1.4410 
S_Dbw validity index (Both):	2.0703 
```

**Comment by gavinha** [comment]
Hi @fpbarthel 

Thanks for these excellent comparisons. From my experience with other samples, sometimes the SDbw are so similar to each other between solutions that it's difficult to distinguish/rank without manual inspection. 

> It looks like although these changes have a dramatic effect on the `SDbw`, the `SDbw` values for the inferior 2a are consistently lower. It looks like this may be a case for manual review.
> 
> Here are some observations:
> 
> * Keeping the 3rd cluster in (2a) with correctResult = `FALSE` led to an expected (i guess?) increase in overall Sdbw
> * Yet, even with correctResult = `FALSE`, the overall Sdbw in 2a < 2b
> * The LogRatio SDbw is lower in 2b compared to 2a (is there any reason why this could be used for selection?), but the AllelicRatio SDbw is higher

In the original version of the code (the version used for the paper), it was only the log ratio that was used, I believe. Of course, there were some cases that this didn't work well so I added in the allelic ratio SDbw as well. Perhaps for some situations, using only the SDbw based on log ratios may be more appropriate. 

> * The superior solution 2b has a slightly higher log likelihood with correctResults = `TRUE` (identical to the logliks in my post above) but without correction, the log likelihood is higher in the inferior solution 2a

You can imagine for samples where all solutions are equally difficult to select, the `correctResults=TRUE` can help so that at least there's some decent processing done for at least one of the solutions.  In this situation, I'm not sure if it helped. 

Overall, solution 2a is overfitting to subclonal gains. Another post-processing step we can try is to exclude solutions that have more than XX% of the genome being predicted as subclonal. This is what I've done for ichorCNA:
https://github.com/broadinstitute/ichorCNA/blob/4260c64e3be6d36772aa253b4ef8bc306a63eb26/scripts/runIchorCNA.R#L39-L40

**Comment by fpbarthel** [comment]
> Overall, solution 2a is overfitting to subclonal gains. Another post-processing step we can try is to exclude solutions that have more than XX% of the genome being predicted as subclonal.

Is there a way to do this using the params output? Or just calculate using the seg file?

I think I understand most of the params output, except for:

```
Clonal cluster cellular prevalence Z=2:	0.9718 0.5857
```
The number of values here seems to match the number of clusters, but the values don't match the horizontal lines in the CP plot?

```
AllelicRatio binomial means for clonal cluster Z=1:	0.5 0.7018 0.7875 0.5332 0.835 0.6117 0.8651 0.6825 0.5421 0.8859 0.7315 0.5772 0.9012 0.7674 0.6337 0.5463 0.9128 0.7949 0.6769 0.559 0.922 0.8165 0.711 0.6055 0.5487
logRatio Gaussian means for clonal cluster Z=1:	-1.175 -0.4296 0.05949 0.05949 0.4241 0.4241 0.7149 0.7149 0.7149 0.9568 0.9568 0.9568 1.164 1.164 1.164 1.164 1.345 1.345 1.345 1.345 1.506 1.506 1.506 1.506 1.506
AllelicRatio binomial means for clonal cluster Z=2:	0.5 0.6048 0.6733 0.52 0.7215 0.5738 0.7574 0.6287 0.5297 0.785 0.671 0.557 0.807 0.7047 0.6023 0.5354 0.8249 0.7321 0.6393 0.5464 0.8398 0.7549 0.6699 0.585 0.5392
logRatio Gaussian means for clonal cluster Z=2:	-0.5543 -0.215 0.05949 0.05949 0.29 0.29 0.4887 0.4887 0.4887 0.6634 0.6634 0.6634 0.8191 0.8191 0.8191 0.8191 0.9597 0.9597 0.9597 0.9597 1.088 1.088 1.088 1.088 1.088
logRatio Gaussian variance:	0.009981 0.01016 0.009034 0.009034 0.009998 0.009998 0.01006 0.01006 0.01006 0.009995 0.009995 0.009995 0.009976 0.009976 0.009976 0.009976 0.009996 0.009996 0.009996 0.009996 0.01015 0.01015 0.01015 0.01015 0.01015
```
What do these 25 values indicate? 23 chromosomes + 2?

**Comment by udp3f** [comment]
With reference to the "S_Dbw validity index" I see that the params file outputs this index for log ratio, allelic ratio as well as both. In choosing the best cluster solution, which one of these need to be considered for the lowest value across all run cluster initializations?

**Comment by gavinha** [comment]
Hi @udp3f 

By default, the snakemake pipeline uses `Both` but if you feel that the data quality for either one of `log ratio` or `allelic ratio` is sub-par, then you may choose to use one of them.

-Gavin
