### ISSUE TITLE
Can Titan deal with WES data?

### ISSUE THREAD

**Issue by snoopy-448** [gavinha/TitanCNA#47]
Hi
I want to use TitanCNA and PhyloWGS on my WES data. I noticed that these tools are designed for WGS, so I wonder that have you tried TitanCNA on WES data and does it work well?
Many thanks!

Yang

**Comment by gavinha** [comment]
Hi @snoopy-448 

Yes, you can use TitanCNA for WES data. If you plan to use the snakemake pipeline, then you need to specify the exon bait set intervals here:
https://github.com/gavinha/TitanCNA/blob/e214ca3f426f82939067b521fed9f7bf2a710dd8/scripts/snakemake/config/config.yaml#L18

Hope this helps.

Best,
Gavin

**Comment by snoopy-448** [comment]
Thanks for your reply!
I encountered another problem. It seems that the snakemake pipeline need to download some reference files, but the compute nodes of our server cannot connect to network. Is there some workaround, such as downloading these files by myself and input there path in the config file?

**Comment by snoopy-448** [comment]
Oh I got it, I have not install BSgenome.Hsapiens.UCSC.hg19 locally. Sorry to bother you!
