### ISSUE TITLE
Snakemake ChildIOExcpetion

### ISSUE THREAD

**Issue by aleighgreen** [gavinha/TitanCNA#49]
`snakemake -s ichorCNA.snakefile -np`
Building DAG of jobs...
ChildIOException:
File/directory is a child to another output:
/spin1/home/TitanCNA/scripts/snakemake/results/ichorCNA/tumor_X
/spin1/home/TitanCNA/scripts/snakemake/results/ichorCNA/tumor_X/tumor_X.cna.seg

As per error #26 , switching back from snakemake 5.3 to 3.8 seemed to resolve the problem, but I wanted to make the problem visible.

**Comment by gavinha** [comment]
@aleighgreen 

I am starting to upgrade all my snakemake pipelines.  So far, I've done it for the [TitanCNA_10X](https://github.com/gavinha/TitanCNA_10X_snakemake) pipeline but I'm slowly making my way to the original TitanCNA.

The good news is I know how to do it.  The bad news is I have limited time to work on things not immediately required for my projects.
