### ISSUE TITLE
No results, no exception thrown with failed ichorCNA snakemake 

### ISSUE THREAD

**Issue by MUppal** [gavinha/TitanCNA#59]
Hi, I'm having trouble having the snakemake output results. I'm attempting to run the command "snakemake -s ichorCNA.snakefile -np" and get the following output (see below). I unfortunately can't tell clearly the error from the output, as the output does not explicitly throw an exception or state which process/dependency might be improperly linked to in config.yaml. It would seem that the output of the command would be in the "results" directory, but there is none to be found. 

I'm using the following versions of software:
TitanCNA - 1.17.0 (I believe the current version in the Titan snakemake repo)
ichorCNA - 0.1.0
HMMcopy - 1.24.0
optparse - 1.6.0
SNPchip - 2.28.0
stringr - 1.3.1

Python-3.5.2
snakemake - 3.12.0
PySAM-0.15.1
PyYAML-3.13

samtools-1.3.1
HMM_Copy_Utils-1.0

rule read_counter:
    input: /home/ubuntu/Sample_PM1043_Z11_1_p2_Case_HALO.md.bam
    output: results/readDepth/tumor_sample_1.bin10000.wig
    log: logs/readDepth/tumor_sample_1.bin10000.log
    jobid: 1
    wildcards: samples=tumor_sample_1, binSize=10000
    resources: mem=4

/home/ubuntu/hmmcopy_utils/bin/readCounter /home/ubuntu/Sample_PM1043_Z11_1_p2_Case_HALO.md.bam -c 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y -w 10000 -q 20 > results/readDepth/tumor_sample_1.bin10000.wig 2> logs/readDepth/tumor_sample_1.bin10000.log

rule read_counter:
    input: /home/ubuntu/Sample_PM1043_EBC4_2_p2_Ctrl_HALO.md.bam
    output: results/readDepth/normal_sample_1.bin10000.wig
    log: logs/readDepth/normal_sample_1.bin10000.log
    jobid: 3
    wildcards: samples=normal_sample_1, binSize=10000
    resources: mem=4

/home/ubuntu/hmmcopy_utils/bin/readCounter /home/ubuntu/Sample_PM1043_EBC4_2_p2_Ctrl_HALO.md.bam -c 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y -w 10000 -q 20 > results/readDepth/normal_sample_1.bin10000.wig 2> logs/readDepth/normal_sample_1.bin10000.log

rule ichorCNA:
    input: results/readDepth/tumor_sample_1.bin10000.wig, results/readDepth/normal_sample_1.bin10000.wig
    output: results/ichorCNA/tumor_sample_1/tumor_sample_1.correctedDepth.txt, results/ichorCNA/tumor_sample_1/, results/ichorCNA/tumor_sample_1/tumor_sample_1.cna.seg
    log: logs/ichorCNA/tumor_sample_1.log
    jobid: 2
    wildcards: tumor=tumor_sample_1
    resources: mem=4

Rscript /home/ubuntu/ichorCNA/scripts/runIchorCNA.R --libdir /home/ubuntu/ichorCNA/R/ --id tumor_sample_1 --WIG results/readDepth/tumor_sample_1.bin10000.wig --gcWig /home/ubuntu/ichorCNA/inst/extdata/gc_hg19_10kb.wig --mapWig /home/ubuntu/ichorCNA/inst/extdata/map_hg19_10kb.wig --NORMWIG results/readDepth/normal_sample_1.bin10000.wig --ploidy "c(2,3)" --normal "c(0.5)" --maxCN 8 --includeHOMD False --genomeStyle NCBI --chrs "c(1:22, \"X\")" --estimateNormal True --estimatePloidy True --estimateScPrevalence True --scStates "c(1,3)" --centromere /home/ubuntu/ichorCNA/inst/extdata/GRCh37.p13_centromere_UCSC-gapTable.txt --exons.bed None --txnE 0.9999 --txnStrength 10000 --fracReadsInChrYForMale 0.001 --plotFileType png --plotYLim "c(-2,4)" --outDir results/ichorCNA/tumor_sample_1/ > logs/ichorCNA/tumor_sample_1.log 2> logs/ichorCNA/tumor_sample_1.log

localrule correctDepth:
    input: results/ichorCNA/tumor_sample_1/tumor_sample_1.cna.seg, results/ichorCNA/tumor_sample_1/tumor_sample_1.correctedDepth.txt, results/readDepth/tumor_sample_1.bin10000.wig, results/readDepth/normal_sample_1.bin10000.wig
    jobid: 0

Job counts:
	count	jobs
	1	correctDepth
	1	ichorCNA
	2	read_counter
	4

Any help would be appreciated! Thank you!

**Comment by gavinha** [comment]
Hi @MUppal 

For snakemake, if you use `-np`, it does not actually run the pipeline, but rather just displays information. For more information on snakemake, you can check out their documentation.

Best,
Gavin
