### ISSUE TITLE
Should Corrected_Ratio be NA in the .segs files?

### ISSUE THREAD

**Issue by aleighgreen** [gavinha/TitanCNA#67]
Just wondering if this output is expected? It seems that Corrected_Ratio is NA in all rows in all the *.segs files in my samples. 

<img width="1032" alt="screen shot 2019-02-08 at 2 00 16 pm" src="https://user-images.githubusercontent.com/7161524/52499677-f4eab280-2ba9-11e9-9a2e-29bdfe13740e.png">

**Comment by gavinha** [comment]
Hi @aleighgreen 

Thanks for catching this bug. I pushed a fix, which should hopefully correct this issue. Please re-open the issue if this doesn't solve it.

Thanks,
Gavin
