### ISSUE TITLE
selectSolution script expects files with wrong names

### ISSUE THREAD

**Issue by lbeltrame** [gavinha/TitanCNA#7]
The main TitanCNA script generates file with `param` in their names for parameters. However, `selectSolution` looks (using `list.files`) for files using `params` as pattern, and therefore does not run to completion because all file lists are empty.

**Comment by gavinha** [comment]
Hi Luca,

There is indeed a typo here:
https://github.com/gavinha/TitanCNA/blob/a55005a17b941ceeacf6cbe7986e63d6ba722238/scripts/R_scripts/titanCNA.R#L115-L117

However, this is only used if the user does not supply an output file name for this.  In the snakemake workflow, it does supply one directly and it uses `params.txt`.  
Thanks for catching this.  I'll make the fix.

Best,
Gavin
