### ISSUE TITLE
Run Titan on tumor-only WGS sample

### ISSUE THREAD

**Issue by ysbioinfo** [gavinha/TitanCNA#91]
Hello,
I want to apply titanCNA on my WGS data, however I only have tumor samples without matched normal. Can Titan deal with this?
Thanks alot!

Yang

**Comment by npatel-ah** [comment]
Hello Yang, Were you able to run this for Tumor Only WGS sample ?

**Comment by gavinha** [comment]
Hi @YangShi-PKU  and @Admera2020 

Here’s a Titan workflow that might help. 
https://github.com/GavinHaLab/TitanCNA_SV_WGS_tumorOnly

Best,
Gavin
